export function libraries() {
  return [
    {
      id: 1,
      name: 'Liked Songs',
      imgUrl: 'https://source.unsplash.com/random/300×300',
      pinned: true,
      type: 'Playlist',
      description: '59 songs',
    },
    {
      id: 2,
      name: 'You don\'t know me',
      imgUrl: 'https://source.unsplash.com/random/300×300',
      pinned: true,
      type: 'Playlist',
      description: 'Kamaleshpathy VA',
    },
    {
      id: 3,
      name: 'Nolan\'s',
      imgUrl: 'https://source.unsplash.com/random/300×300',
      pinned: false,
      type: 'Playlist',
      description: 'Kamaleshpathy VA',
    },
    {
      id: 4,
      name: 'HipHop Tamizha',
      imgUrl: 'https://source.unsplash.com/random/300×300',
      pinned: false,
      type: 'Artist',
      description: null,
    },
    {
      id: 5,
      name: 'Emma Hesters',
      imgUrl: 'https://source.unsplash.com/random/300×300',
      pinned: false,
      type: 'Artist',
      description: null,
    },
    {
      id: 6,
      name: 'Sherlock',
      imgUrl: 'https://source.unsplash.com/random/300×300',
      pinned: false,
      type: 'Album',
      description: 'David Arnold',
    },
    {
      id: 4,
      name: 'HipHop Tamizha',
      imgUrl: 'https://source.unsplash.com/random/300×300',
      pinned: false,
      type: 'Artist',
      description: null,
    },
    {
      id: 5,
      name: 'Emma Hesters',
      imgUrl: 'https://source.unsplash.com/random/300×300',
      pinned: false,
      type: 'Artist',
      description: null,
    },
    {
      id: 6,
      name: 'Sherlock',
      imgUrl: 'https://source.unsplash.com/random/300×300',
      pinned: false,
      type: 'Album',
      description: 'David Arnold',
    },
  ]
}